version: '2'

services:
  videar-setup:
    build: 
      context: .
      dockerfile: dockerbuilds/Dockerfile-main
    volumes:
      - /usr/src/videar
    environment:
      - DB_HOST=central_mongodb

  java_s2t-setup:
    build:
      context: .
      dockerfile: dockerbuilds/Dockerfile-java_s2t
    volumes:
      - /usr/src/s2t
    environment:
      - SPRING_VIDEAR_DB_HOST=central_mongodb
