FROM mkaichen/node-ubuntu

ENV S2T_DIR /usr/src/s2t

# Create app directory
RUN mkdir -p $S2T_DIR
WORKDIR $S2T_DIR

# move everything
COPY ./services/speech2text $S2T_DIR

EXPOSE 8000
CMD [ "node", "server.js" ]
