FROM mkaichen/node-ubuntu

ENV NODE_ENV=test
ENV VIDEAR_DIR /usr/src/videar

# Create app directory
RUN mkdir -p $VIDEAR_DIR
WORKDIR $VIDEAR_DIR

# move everything
COPY ./services/main $VIDEAR_DIR

# setup everything
RUN bash setup.sh
RUN npm install mocha -g

CMD [ "mocha", "tests", "--recursive" ]
